package main

import (
	"fmt"
	"strings"
)

// Markdown report output. Goal: render that drops cleanly into a GitHub
// issue / PR description / Slack thread without further editing. Uses
// GFM-flavoured tables, fenced code blocks for hints, and emoji status
// badges so it reads correctly on every markdown renderer worth caring
// about.

func renderMarkdown(r Report) string {
	var b strings.Builder
	b.WriteString("# netdoc report — `")
	b.WriteString(r.Target)
	b.WriteString("`\n\n")

	if r.Healthy {
		b.WriteString("**Status:** ✅ Healthy — no problems found  \n")
	} else {
		fmt.Fprintf(&b, "**Status:** ❌ %d problem%s  \n", len(r.Problems), plural(len(r.Problems)))
	}
	fmt.Fprintf(&b, "**Elapsed:** %s  \n", r.Elapsed)
	fmt.Fprintf(&b, "**netdoc:** %s\n\n", version)

	if !r.Healthy && r.FixFirst != "" {
		b.WriteString("> 🔧 **Fix first:** ")
		b.WriteString(r.FixFirst)
		b.WriteString("\n\n")
	}

	b.WriteString("| Check | Status | Summary |\n")
	b.WriteString("|---|---|---|\n")
	for _, c := range r.Checks {
		icon := "·"
		switch c.Status {
		case StatusOK:
			icon = "✅"
		case StatusWarn:
			icon = "⚠️"
		case StatusFail:
			icon = "❌"
		case StatusSkip:
			icon = "⏭️"
		}
		summary := strings.ReplaceAll(c.Summary, "|", "\\|")
		fmt.Fprintf(&b, "| **%s** | %s | %s |\n", c.Name, icon, summary)
	}

	// Per-check detail with hints in fenced code blocks. Skip checks
	// with no hint to keep the report compact for healthy results.
	for _, c := range r.Checks {
		if c.Hint == "" {
			continue
		}
		fmt.Fprintf(&b, "\n### %s\n\n", c.Name)
		b.WriteString("```\n")
		b.WriteString(c.Hint)
		if !strings.HasSuffix(c.Hint, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("```\n")
	}

	if !r.Healthy && len(r.Problems) > 0 {
		b.WriteString("\n### Problems\n\n")
		for _, p := range r.Problems {
			b.WriteString("- ")
			b.WriteString(p)
			b.WriteString("\n")
		}
	}

	b.WriteString("\n---\n_Generated by [netdoc](https://github.com/firaszaarouri/netdoc)._\n")
	return b.String()
}
