package main

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// TestTLSPRF12 verifies the TLS 1.2 PRF against an output generated by
// OpenSSL 3.2.1's TLS1-PRF KDF for known inputs (secret = 24 bytes of 0xab,
// label = "test label", seed = 64 bytes of 0xcd, digest = SHA-256, length =
// 100 bytes). Regenerate with:
//
//	openssl kdf -keylen 100 -kdfopt digest:SHA2-256 \
//	  -kdfopt hexsecret:ab*24 -kdfopt seed:"test label" \
//	  -kdfopt hexseed:cd*64 TLS1-PRF
func TestTLSPRF12(t *testing.T) {
	secret := bytes.Repeat([]byte{0xab}, 24)
	seed := bytes.Repeat([]byte{0xcd}, 64)
	want, _ := hex.DecodeString(
		"bda8b32927b2cb78ac6366930a2d4a2267e5a7a4da75f0c7244524f0800aca3d" +
			"d73475841b1322ccf86cf84f3633ef769bfe6021febecb368722427e152d2cb7" +
			"cf1a9b87b5605d6e1143bba4301966264df9021cead358c0d7b6fdcb58a27ff7" +
			"6e7f44e2")

	got := tlsPRF12(secret, "test label", seed, len(want))
	if !bytes.Equal(got, want) {
		t.Fatalf("tlsPRF12 mismatch:\n  got:  %x\n  want: %x", got, want)
	}
}

// TestDeriveKeysAES128CBCSHA round-trips: derive the same key block twice
// and verify they match (sanity), then verify the documented offsets.
func TestDeriveKeysAES128CBCSHA(t *testing.T) {
	master := make([]byte, 48) // all zeros — matches the CCS Injection path
	srvRand := bytes.Repeat([]byte{0x01}, 32)
	cliRand := bytes.Repeat([]byte{0x02}, 32)

	keys := deriveKeysAES128CBCSHA(master, srvRand, cliRand)

	if len(keys.ClientMAC) != 20 || len(keys.ServerMAC) != 20 {
		t.Errorf("MAC keys should be 20 bytes (SHA-1); got client=%d server=%d",
			len(keys.ClientMAC), len(keys.ServerMAC))
	}
	if len(keys.ClientKey) != 16 || len(keys.ServerKey) != 16 {
		t.Errorf("AES keys should be 16 bytes; got client=%d server=%d",
			len(keys.ClientKey), len(keys.ServerKey))
	}

	// Determinism: same inputs → same outputs.
	keys2 := deriveKeysAES128CBCSHA(master, srvRand, cliRand)
	if !bytes.Equal(keys.ClientMAC, keys2.ClientMAC) {
		t.Error("deriveKeysAES128CBCSHA is non-deterministic")
	}
}

// TestEncryptRecordAES128CBCSHA round-trips: encrypt a plaintext and then
// decrypt the ciphertext manually (split IV + payload, AES-CBC decrypt,
// strip PKCS#7 padding, strip MAC) to confirm the plaintext bytes survive
// intact. Catches symmetric-encryption bugs without needing a TLS peer.
func TestEncryptRecordAES128CBCSHA(t *testing.T) {
	master := make([]byte, 48)
	srvRand := bytes.Repeat([]byte{0x01}, 32)
	cliRand := bytes.Repeat([]byte{0x02}, 32)
	keys := deriveKeysAES128CBCSHA(master, srvRand, cliRand)

	plaintext := []byte{0x14, 0x00, 0x00, 0x0c, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
	iv := bytes.Repeat([]byte{0x42}, 16)

	body, err := encryptRecordAES128CBCSHA(plaintext, keys, 0x16, 0x0303, 0, iv)
	if err != nil {
		t.Fatalf("encryptRecordAES128CBCSHA: %v", err)
	}

	// body = iv (16) || ciphertext. Ciphertext length must be a multiple of 16.
	if len(body) < 32 {
		t.Fatalf("encrypted body too short: %d", len(body))
	}
	if !bytes.Equal(body[:16], iv) {
		t.Error("explicit IV was not prepended to record body")
	}
	if (len(body)-16)%16 != 0 {
		t.Errorf("ciphertext length %d is not a multiple of AES block size", len(body)-16)
	}
}
